// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6651.SliderDT;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainSpeedController1-2;
    public static SpeedController driveTrainSpeedController3-4;
    public static DifferentialDrive driveTrainDifferentialDrive1;
    public static SpeedController driveTrainSpeedController5;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainSpeedController1-2 = new Spark(0);
        LiveWindow.addActuator("DriveTrain", "Speed Controller 1-2", (Spark) driveTrainSpeedController1-2);
        driveTrainSpeedController1-2.setInverted(false);
        
        driveTrainSpeedController3-4 = new Spark(2);
        LiveWindow.addActuator("DriveTrain", "Speed Controller 3-4", (Spark) driveTrainSpeedController3-4);
        driveTrainSpeedController3-4.setInverted(false);
        
        driveTrainDifferentialDrive1 = new DifferentialDrive(driveTrainSpeedController1-2, driveTrainSpeedController3-4);
        LiveWindow.addActuator("DriveTrain", "Differential Drive 1", driveTrainDifferentialDrive1);
        
        driveTrainDifferentialDrive1.setSafetyEnabled(true);
        driveTrainDifferentialDrive1.setExpiration(0.1);
        driveTrainDifferentialDrive1.setMaxOutput(1.0);

        driveTrainSpeedController5 = new Spark(4);
        LiveWindow.addActuator("DriveTrain", "Slide Controller", (Spark) driveTrainSpeedController5);
        driveTrainSpeedController5.setInverted(false);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
